#Site settings
title: CAIP Hub
description: A configurable program capable of file integrity checks and program execution.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://caippy.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/caip-icon.png"

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "CAIP on GitHub":
    - "//github.com/ChrispyMC/CAIP"
  "CAIP on Itch":
    - "//cih.itch.io/caip"
  "CAIP Languages on GitHub":
    - "//github.com/ChrispyMC/CAIP-Languages"

# Footer content appears at the bottom of every page's main content
footer_content: "CAIP &copy; 2018-2020, Christopher Ying, and the CAIP Developers."

# Color scheme currently only supports "dark" or nil (default)
color_scheme: "dark"

# Remote Theme
remote_theme: ChrispyMC/just-the-docs
